all:
	gcc -o sum sum.c list.c -g -W
	gcc -o sum-codeblocks sum-codeblocks.c -g -W
	gcc -o in in.c list.c -g -W
	gcc -o in-codeblocks in-codeblocks.c -g -W
	gcc -o size size.c list.c -g -W
	gcc -o size-codeblocks size-codeblocks.c -g -W
	gcc -o position position.c list.c -g -W
	gcc -o position-codeblocks position-codeblocks.c  -g -W
	gcc -o merge merge.c list.c -g -W
	gcc -o merge-codeblocks merge-codeblocks.c -g -W
	gcc -o sudoku sudoku.c -g -W
clean:
	rm sum sum-codeblocks in in-codeblocks size size-codeblocks position position-codeblocks merge merge-codeblocks sudoku
