main: main_codifica.c trabalho1.h
	gcc t1-2556618.c main_codifica.c trabalho1.c trabalho1.h imagem.c imagem.h -o main -lm -W -Wall -pedantic -g3 -O0
teste: teste.c 
	gcc teste.c -o teste -lm -W -Wall -pedantic -g3 -O0
