2: exercicio_2.c
	gcc exercicio_2.c -o exercicio2 -lm
3: exercicio_3.c
	gcc exercicio_3.c -o exercicio3 -lm
4: exercicio_4.c
	gcc exercicio_4.c -o exercicio4 -lm
5: exercicio_5.c
	gcc exercicio_5.c -o exercicio5 -lm
