1a: atividade_1a.c
	gcc atividade_1a.c -o atividade1a -lm
1b: atividade_1b.c
	gcc atividade_1b.c -o atividade1b -lm
1c: atividade_1c.c
	gcc atividade_1c.c -o atividade1c -lm
2: atividade_2.c
	gcc atividade_2.c -o atividade2 -lm
3: atividade_3.c
	gcc atividade_3.c -o atividade3 -lm
4: atividade_4.c
	gcc atividade_4.c -o atividade4 -lm
5: atividade_5.c
	gcc atividade_5.c -o atividade5 -lm
