teste0: teste0_basico.c trabalho2.h wavfile.c wavfile.h
	gcc teste0_basico.c  trabalho2.h wavfile.c wavfile.h -o teste -lm -W -Wall -pedantic -g3 -O0
teste1: t2-2556618-2556693.c teste1_ganho.c trabalho2.h  wavfile.c wavfile.h
	gcc t2-2556618-2556693.c teste1_ganho.c trabalho2.h  wavfile.c wavfile.h -o teste1 -lm -W -Wall -pedantic -g3 -O0
teste2: t2-2556618-2556693.c teste2_mistura.c trabalho2.h  wavfile.c wavfile.h
	gcc t2-2556618-2556693.c teste2_mistura.c trabalho2.h  wavfile.c wavfile.h -o teste2 -lm -W -Wall -pedantic -g3 -O0
teste3: t2-2556618-2556693.c teste3_inverte.c trabalho2.h  wavfile.c wavfile.h
	gcc t2-2556618-2556693.c teste3_inverte.c trabalho2.h  wavfile.c wavfile.h -o teste3 -lm -W -Wall -pedantic -g3 -O0
teste4: t2-2556618-2556693.c teste4_atraso.c trabalho2.h  wavfile.c wavfile.h
	gcc t2-2556618-2556693.c teste4_atraso.c trabalho2.h  wavfile.c wavfile.h -o teste4 -lm -W -Wall -pedantic -g3 -O0
teste5: t2-2556618-2556693.c teste5_media.c trabalho2.h  wavfile.c wavfile.h
	gcc t2-2556618-2556693.c teste5_media.c trabalho2.h  wavfile.c wavfile.h -o teste5 -lm -W -Wall -pedantic -g3 -O0
teste6: t2-2556618-2556693.c teste6_ecos.c trabalho2.h  wavfile.c wavfile.h
	gcc t2-2556618-2556693.c teste6_ecos.c trabalho2.h  wavfile.c wavfile.h -o teste6 -lm -W -Wall -pedantic -g3 -O0
