1: atividade_1.c
	gcc atividade_1.c -o atividade1 -O0 -g3 -lm  -W -Wall -pedantic
2: atividade_2.c
	gcc atividade_2.c -o atividade2 -O0 -g3 -lm  -W -Wall -pedantic
1: atividade_1.c
	gcc atividade_1.c -o atividade1 -O0 -g3 -lm  -W -Wall -pedantic
2: atividade_2.c
	gcc atividade_2.c -o atividade2 -O0 -g3 -lm  -W -Wall -pedantic
1: atividade_1.c
	gcc atividade_1.c -o atividade1 -O0 -g3 -lm  -W -Wall -pedantic
2: atividade_2.c
	gcc atividade_2.c -o atividade2 -O0 -g3 -lm  -W -Wall -pedantic
