1: atividade_1.c
	gcc atividade_1.c -o atividade1 -lm
2: atividade_2.c
	gcc atividade_2.c -o atividade2 -lm
3: atividade_3.c
	gcc atividade_3.c -o atividade3 -lm
4: atividade_4.c
	gcc atividade_4.c -o atividade4 -lm
