all:
	gcc -o par_impar par_impar.c queue.c -g -W
	gcc -o par_impar_codeblocks par_impar_codeblocks.c  -g -W
	gcc -o islands islands.c pqueue.c -g -W
	gcc -o imagens imagens.c pqueue.c -g -W
	gcc -o jackpot jackpot.c queue.c -g -W
clean:
	rm par_impar par_impar_codeblocks islands imagens jackpot
