1: atividade_1.c
	gcc atividade_1.c -o atividade1 -O0 -g3 -lm  -W -Wall -pedantic
2: atividade_2.c
	gcc atividade_2.c -o atividade2 -O0 -g3 -lm  -W -Wall -pedantic
3: atividade_3.c
	gcc atividade_3.c -o atividade3 -O0 -g3 -lm  -W -Wall -pedantic
4: atividade_4.c
	gcc atividade_4.c -o atividade4 -O0 -g3 -lm  -W -Wall -pedantic
desafio: desafio.c
	gcc desafio.c -o desafio -O0 -g3 -lm  -W -Wall -pedantic
