all:
	gcc -o elimina-par elimina-par.c stack.c -g -W
	gcc -o elimina-par-codeblocks elimina-par-codeblocks.c  -g -W
	gcc -o maze maze.c pstack.c -g -W
	gcc -o parser parser.c stack.c -g -W
	gcc -o polish polish.c stack.c -g -W
	gcc -o reverse reverse.c stack.c queue.c -g -W
	gcc -o minesweeper minesweeper.c pstack.c -g -W
clean:
	rm elimina-par elimina-par-codeblocks maze parser polish reverse minesweeper

