all:
	gcc -o elimina-par elimina-par.c stack.c
	gcc -o elimina-par-codeblocks elimina-par-codeblocks.c 
	gcc -o maze maze.c pstack.c
	gcc -o parser parser.c stack.c
	gcc -o polish polish.c stack.c
	gcc -o reverse reverse.c stack.c queue.c
	gcc -o minesweeper minesweeper.c pstack.c
clean:
	rm elimina-par elimina-par-codeblocks maze parser polish reverse minesweeper

