codifica: main_codifica.c trabalho1.h t1-2556618.c trabalho1.c imagem.c imagem.h
	gcc t1-2556618.c main_codifica.c trabalho1.c trabalho1.h imagem.c imagem.h -o codifica -lm -W -Wall -pedantic -g3 -O0
decodifica: main_decodifica.c trabalho1.h t1-2556618.c trabalho1.c imagem.c imagem.h
	gcc t1-2556618.c main_decodifica.c trabalho1.c trabalho1.h imagem.c imagem.h -o decodifica -lm -W -Wall -pedantic -g3 -O0
teste: teste.c 
	gcc teste.c -o teste -lm -W -Wall -pedantic -g3 -O0
