main: t3-2556618-2556693-2505568.c trabalho3.h imagem.c imagem.h gerador_de_testes.h gerador_de_testes.c main.c
	gcc t3-2556618-2556693-2505568.c main.c imagem.c imagem.h  gerador_de_testes.h gerador_de_testes.c trabalho3.h -o main -lm -W -Wall -pedantic -g3 -O0
vito: trabalho3.c trabalho3.h imagem.c imagem.h gerador_de_testes.h gerador_de_testes.c main.c
	gcc trabalho3.c main.c imagem.c imagem.h  gerador_de_testes.h gerador_de_testes.c trabalho3.h -o main -lm -W -Wall -pedantic -g3 -O0
teste: teste.c
	gcc teste.c -o teste -lm -W -Wall -pedantic -g3 -O0
